// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://avlgrjenabtkmpmtpkrn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF2bGdyamVuYWJ0a21wbXRwa3JuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUwNDU4NTMsImV4cCI6MjA3MDYyMTg1M30.5Tw9q-Kse3XmGe0CBxQJ4lANaFKXX2X1iWIq9n6yjE0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});